# Generated by Django 4.2.6 on 2023-11-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('docente', 'Docente'), ('mantenimiento', 'Personal de Mantenimiento')], max_length=255),
        ),
    ]
