# Generated by Django 4.2.6 on 2023-11-29 06:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0003_almacen_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_almacen', models.CharField(max_length=255)),
                ('nombre_persona', models.CharField(max_length=255)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.almacen')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.persona')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.producto')),
            ],
        ),
    ]
