-- MySQL Script generated by MySQL Workbench
-- Tue May 21 12:27:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uacm_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uacm_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS uacm_2 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE uacm_2 ;

-- -----------------------------------------------------
-- Table uacm_2.almacen_app_almacen
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_almacen (
  id_almacen INT NOT NULL AUTO_INCREMENT,
  tipo_almacen VARCHAR(255) NOT NULL,
  direccion LONGTEXT NOT NULL,
  correo VARCHAR(254) NOT NULL,
  telefono VARCHAR(15) NOT NULL,
  PRIMARY KEY (id_almacen))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_rol
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_rol (
  id_rol INT NOT NULL AUTO_INCREMENT,
  nombre_rol VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_rol))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_persona
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_persona (
  id_persona INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  apellido_paterno VARCHAR(255) NOT NULL,
  apellido_materno VARCHAR(255) NOT NULL,
  telefono VARCHAR(15) NOT NULL,
  correo VARCHAR(254) NOT NULL,
  contrasena VARCHAR(255) NOT NULL,
  id_rol_id INT NOT NULL,
  PRIMARY KEY (id_persona),
  INDEX almacen_app_persona_id_rol_id_1db5b701_fk_almacen_app_rol_id_rol (id_rol_id ASC) VISIBLE,
  CONSTRAINT almacen_app_persona_id_rol_id_1db5b701_fk_almacen_app_rol_id_rol
    FOREIGN KEY (id_rol_id)
    REFERENCES uacm_2.almacen_app_rol (id_rol))
ENGINE = InnoDB
AUTO_INCREMENT = 457
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_producto
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_producto (
  id_producto INT NOT NULL AUTO_INCREMENT,
  nombre_producto VARCHAR(255) NOT NULL,
  cantidad INT NOT NULL,
  PRIMARY KEY (id_producto))
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_solicitud
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_solicitud (
  id_solicitud INT NOT NULL AUTO_INCREMENT,
  tipo_almacen VARCHAR(255) NOT NULL,
  nombre_persona VARCHAR(255) NOT NULL,
  nombre_producto VARCHAR(255) NOT NULL,
  cantidad INT NOT NULL,
  fecha_solicitud DATETIME(6) NOT NULL,
  id_almacen_id INT NOT NULL,
  id_persona_id INT NOT NULL,
  id_producto_id INT NOT NULL,
  PRIMARY KEY (id_solicitud),
  INDEX almacen_app_solicitu_id_almacen_id_cfcddcd5_fk_almacen_a (id_almacen_id ASC) VISIBLE,
  INDEX almacen_app_solicitu_id_persona_id_eb47dc22_fk_almacen_a (id_persona_id ASC) VISIBLE,
  INDEX almacen_app_solicitu_id_producto_id_2a5cc257_fk_almacen_a (id_producto_id ASC) VISIBLE,
  CONSTRAINT almacen_app_solicitu_id_almacen_id_cfcddcd5_fk_almacen_a
    FOREIGN KEY (id_almacen_id)
    REFERENCES uacm_2.almacen_app_almacen (id_almacen),
  CONSTRAINT almacen_app_solicitu_id_persona_id_eb47dc22_fk_almacen_a
    FOREIGN KEY (id_persona_id)
    REFERENCES uacm_2.almacen_app_persona (id_persona),
  CONSTRAINT almacen_app_solicitu_id_producto_id_2a5cc257_fk_almacen_a
    FOREIGN KEY (id_producto_id)
    REFERENCES uacm_2.almacen_app_producto (id_producto))
ENGINE = InnoDB
AUTO_INCREMENT = 301
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_usuario (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nombre_usuario VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL,
  is_staff TINYINT(1) NOT NULL,
  is_superuser TINYINT(1) NOT NULL,
  last_login DATETIME(6) NULL DEFAULT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX nombre_usuario (nombre_usuario ASC) VISIBLE,
  UNIQUE INDEX password (password ASC) VISIBLE,
  UNIQUE INDEX almacen_app_usuario_nombre_usuario_aa2a122c_uniq (nombre_usuario ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.auth_group
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.auth_group (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX name (name ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_usuariogroup
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_usuariogroup (
  id BIGINT NOT NULL AUTO_INCREMENT,
  group_id INT NOT NULL,
  usuario_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  INDEX almacen_app_usuariogroup_group_id_e71bb729_fk_auth_group_id (group_id ASC) VISIBLE,
  INDEX almacen_app_usuariog_usuario_id_e191581f_fk_almacen_a (usuario_id ASC) VISIBLE,
  CONSTRAINT almacen_app_usuariog_usuario_id_e191581f_fk_almacen_a
    FOREIGN KEY (usuario_id)
    REFERENCES uacm_2.almacen_app_usuario (id),
  CONSTRAINT almacen_app_usuariogroup_group_id_e71bb729_fk_auth_group_id
    FOREIGN KEY (group_id)
    REFERENCES uacm_2.auth_group (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.django_content_type
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.django_content_type (
  id INT NOT NULL AUTO_INCREMENT,
  app_label VARCHAR(100) NOT NULL,
  model VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq (app_label ASC, model ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.auth_permission
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.auth_permission (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  content_type_id INT NOT NULL,
  codename VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq (content_type_id ASC, codename ASC) VISIBLE,
  CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co
    FOREIGN KEY (content_type_id)
    REFERENCES uacm_2.django_content_type (id))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.almacen_app_usuariopermission
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.almacen_app_usuariopermission (
  id BIGINT NOT NULL AUTO_INCREMENT,
  permission_id INT NOT NULL,
  usuario_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  INDEX almacen_app_usuariop_permission_id_88af770d_fk_auth_perm (permission_id ASC) VISIBLE,
  INDEX almacen_app_usuariop_usuario_id_d88f65a0_fk_almacen_a (usuario_id ASC) VISIBLE,
  CONSTRAINT almacen_app_usuariop_permission_id_88af770d_fk_auth_perm
    FOREIGN KEY (permission_id)
    REFERENCES uacm_2.auth_permission (id),
  CONSTRAINT almacen_app_usuariop_usuario_id_d88f65a0_fk_almacen_a
    FOREIGN KEY (usuario_id)
    REFERENCES uacm_2.almacen_app_usuario (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.auth_group_permissions
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.auth_group_permissions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  group_id INT NOT NULL,
  permission_id INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq (group_id ASC, permission_id ASC) VISIBLE,
  INDEX auth_group_permissio_permission_id_84c5c92e_fk_auth_perm (permission_id ASC) VISIBLE,
  CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
    FOREIGN KEY (permission_id)
    REFERENCES uacm_2.auth_permission (id),
  CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
    FOREIGN KEY (group_id)
    REFERENCES uacm_2.auth_group (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.auth_user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.auth_user (
  id INT NOT NULL AUTO_INCREMENT,
  password VARCHAR(128) NOT NULL,
  last_login DATETIME(6) NULL DEFAULT NULL,
  is_superuser TINYINT(1) NOT NULL,
  username VARCHAR(150) NOT NULL,
  first_name VARCHAR(150) NOT NULL,
  last_name VARCHAR(150) NOT NULL,
  email VARCHAR(254) NOT NULL,
  is_staff TINYINT(1) NOT NULL,
  is_active TINYINT(1) NOT NULL,
  date_joined DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX username (username ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.auth_user_groups
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.auth_user_groups (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq (user_id ASC, group_id ASC) VISIBLE,
  INDEX auth_user_groups_group_id_97559544_fk_auth_group_id (group_id ASC) VISIBLE,
  CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id
    FOREIGN KEY (group_id)
    REFERENCES uacm_2.auth_group (id),
  CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
    FOREIGN KEY (user_id)
    REFERENCES uacm_2.auth_user (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.auth_user_user_permissions
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.auth_user_user_permissions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  permission_id INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq (user_id ASC, permission_id ASC) VISIBLE,
  INDEX auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm (permission_id ASC) VISIBLE,
  CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
    FOREIGN KEY (permission_id)
    REFERENCES uacm_2.auth_permission (id),
  CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
    FOREIGN KEY (user_id)
    REFERENCES uacm_2.auth_user (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.django_admin_log
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.django_admin_log (
  id INT NOT NULL AUTO_INCREMENT,
  action_time DATETIME(6) NOT NULL,
  object_id LONGTEXT NULL DEFAULT NULL,
  object_repr VARCHAR(200) NOT NULL,
  action_flag SMALLINT UNSIGNED NOT NULL,
  change_message LONGTEXT NOT NULL,
  content_type_id INT NULL DEFAULT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX django_admin_log_content_type_id_c4bce8eb_fk_django_co (content_type_id ASC) VISIBLE,
  INDEX django_admin_log_user_id_c564eba6_fk_auth_user_id (user_id ASC) VISIBLE,
  CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co
    FOREIGN KEY (content_type_id)
    REFERENCES uacm_2.django_content_type (id),
  CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id
    FOREIGN KEY (user_id)
    REFERENCES uacm_2.auth_user (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.django_migrations
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.django_migrations (
  id BIGINT NOT NULL AUTO_INCREMENT,
  app VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  applied DATETIME(6) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table uacm_2.django_session
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS uacm_2.django_session (
  session_key VARCHAR(40) NOT NULL,
  session_data LONGTEXT NOT NULL,
  expire_date DATETIME(6) NOT NULL,
  PRIMARY KEY (session_key),
  INDEX django_session_expire_date_a5c62663 (expire_date ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;